# Generated by Django 5.2.3 on 2025-07-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('credential_validity_days', models.IntegerField(default=7)),
                ('cumulative_usage_quota_minutes', models.IntegerField(default=240)),
                ('first_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_active_time', models.DateTimeField(blank=True, null=True)),
                ('total_minutes_used', models.IntegerField(default=0)),
                ('current_session_start_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_end_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for_deletion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
